core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from product.views import page_not_found

urlpatterns = [
    path("admin/", admin.site.urls),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("", include("product.urls", namespace="product")),

    path("api/product/", include("product.api.urls")),
]

handler404 = page_not_found

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/api/urls.py
from django.urls import path
from product.api.views import product_list_create_view, product_detail_view, index_view, product_create_view, product_delete_view, product_update_put_view, product_update_patch_view

app_name = "product/api"


urlpatterns = [
    path("products/", product_list_create_view, name="products_list_create"), # "GET", "POST"
    path("products/<int:id>", product_detail_view, name="products_detail"),   # "GET", "PUT", "PATCH", "DELETE"
]




# urlpatterns = [
#     path("index/", index_view, name="index"),
#     path("detail/<id>", product_detail_view, name="detail"),
#     path("delete/<id>", product_delete_view, name="delete"),
#     path("create/", product_create_view, name="create"),

#     path("update_put/<id>", product_update_put_view, name="update_put"),
#     path("update_patch/<id>", product_update_patch_view, name="update_patch"),
# ]

product/urls.py
from django.urls import path
from . import views

app_name = "product"

urlpatterns = [
    path("", views.index, name="index"),
    path("home/", views.home, name="home"),
    path("products/", views.product_list, name="product_list"),
    
    # path("products/<int:product_id>/", views.product_detail, name="product_detail"),
    path("products/<slug:slug>/", views.product_detail, name="product_detail"),

    path("products/add/", views.product_add, name="product_add"),
    path("categories/", views.category_list, name="category_list"),
    path("categories/<int:category_id>/", views.category_products, name="category_products"),

    # Usermodel
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register_view, name="register"),

    # Custom
    path("a_login/", views.a_login_view, name="a_login"),
    path("a_logout/", views.a_logout_view, name="a_logout"),
    path("a_register/", views.a_register_view, name="a_register"),
    
    path("a_send_change_password_email/", views.a_send_change_password_email, name="a_send_change_password_email"),
    path("a_confirm_change_password/<uuid:token>/", views.a_confirm_change_password, name="a_confirm_change_password"),



]

product/api/views.py
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework import status
from django.shortcuts import get_object_or_404
from rest_framework.response import Response
from .permissions import IsAuthorAuthenticated  # yuxarıda yazdığımız custom permission

# from product.api.serialize import ProductSerializer, ProductListSerializer, ProductCreateSerializer, ProductUpdateSerializer
from product.api.serialize import (
    ProductListSerializer,
    ProductCreateSerializer,
    ProductUpdateSerializer
)

from product.models import Author, Product
from django.db.models import FloatField, F, ExpressionWrapper, Value, DecimalField
from django.db.models.functions import Coalesce, Round

def annotate_products():
    return Product.objects.annotate(
        discount_price=Coalesce('discount', Value(0), output_field=FloatField()),
        coupon_price=Coalesce('coupon', Value(0), output_field=FloatField()),
        tax=Coalesce('tax_price', Value(0), output_field=FloatField()),
        ).annotate(
        total_price=Round(
            ExpressionWrapper(
                (F('price') * (1 - F('discount_price') / 100) - F('coupon_price') + F('tax')),
                output_field=DecimalField(max_digits=10, decimal_places=2)
            ),
            precision=2
        )
    )

@api_view(["GET", "POST"])
# @permission_classes([IsAuthenticatedOrReadOnly])
@permission_classes([IsAuthorAuthenticated])  # indi bu istifadə olunacaq
def product_list_create_view(request):
    if request.method == "GET":
        products = annotate_products()
        serializer =  ProductListSerializer(products, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)
    
    elif request.method == "POST":
        serializer = ProductCreateSerializer(data=request.data)
        if serializer.is_valid():
        
            try:
                author_id = request.session.get("author_id")
                author = Author.objects.get(id=author_id)
            except (Author.DoesNotExist, TypeError):
                return Response({"error": "Author not found in session"}, status=404)

            serializer.save(author=author)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    

@api_view(["GET", "PUT", "PATCH", "DELETE"])
# @permission_classes([IsAuthorAuthenticated])  # indi bu istifadə olunacaq
def product_detail_view(request, id):
    pruduct = get_object_or_404(annotate_products(), id=id)
    
    if request.method == "GET":
        serializer = ProductListSerializer(pruduct)
        return Response(serializer.data, status=status.HTTP_200_OK)

    elif request.method in ["PUT", "PATCH"]:
        partial = request.method == "PATCH"  # True, False

        serializer = ProductUpdateSerializer(pruduct, data=request.data, partial=partial)

        if serializer.is_valid():
            serializer.save()
            #save olunduqdan sonra melumatlari ekrana cixarsin deye elave olunur
            pruduct = get_object_or_404(annotate_products(), id=id)
            serializer = ProductListSerializer(pruduct)
            return Response(serializer.data, status=status.HTTP_200_OK)
    
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == "DELETE":
        pruduct.delete()
        return Response({"message":"Mehsul ugurla silindi!"}, status=status.HTTP_204_NO_CONTENT)






















# GET, POST, PUT, PATCH, DELETE
# ------------------------------------------------------------------------------
@api_view(["GET"])
def index_view(request):
    # product = Product.objects.all()

    product = Product.objects.annotate(
        discount_price=Coalesce('discount', Value(0), output_field=FloatField()),
        coupon_price=Coalesce('coupon', Value(0), output_field=FloatField()),
        tax=Coalesce('tax_price', Value(0), output_field=FloatField()),
        ).annotate(
        total_price=Round(
            ExpressionWrapper(
                (F('price') * (1 - F('discount_price') / 100) - F('coupon_price') + F('tax')),
                output_field=DecimalField(max_digits=10, decimal_places=2)
            ),
            precision=2
        )
    )

    serializer =  ProductListSerializer(product, many=True)
    print(serializer.data)
    return Response(serializer.data)


@api_view(["GET"])
def product_detail_view(request, id):

    # product = Product.objects.all()
    
    product = Product.objects.annotate(
        discount_price=Coalesce('discount', Value(0), output_field=FloatField()),
        coupon_price=Coalesce('coupon', Value(0), output_field=FloatField()),
        tax=Coalesce('tax_price', Value(0), output_field=FloatField()),
        ).annotate(
        total_price=Round(
            ExpressionWrapper(
                (F('price') * (1 - F('discount_price') / 100) - F('coupon_price') + F('tax')),
                output_field=DecimalField(max_digits=10, decimal_places=2)
            ),
            precision=2
        )
    )

    product = product.get(id=id)
    
    serializer = ProductListSerializer(product, many=False)

    return Response(serializer.data)


@api_view(["POST"])
def product_create_view(request):
    serializer = ProductCreateSerializer(data=request.data)
    serializer.is_valid(raise_exception=True)
    serializer.save()

    return Response(serializer.data)

@api_view(["DELETE"])
def product_delete_view(request, id):
    product = Product.objects.annotate(
        discount_price=Coalesce('discount', Value(0), output_field=FloatField()),
        coupon_price=Coalesce('coupon', Value(0), output_field=FloatField()),
        tax=Coalesce('tax_price', Value(0), output_field=FloatField()),
        ).annotate(
        total_price=Round(
            ExpressionWrapper(
                (F('price') * (1 - F('discount_price') / 100) - F('coupon_price') + F('tax')),
                output_field=DecimalField(max_digits=10, decimal_places=2)
            ),
            precision=2
        )
    )

    product = product.get(id=id)

    product.delete()
    return Response({"Messege":"Product successfully deleted!"})

# ------------------------------------------------------------------------------

@api_view(["PUT"]) # Butun sutunlari update etmek lazimdir. // partial=True lazim deyil
def product_update_put_view(request, id):
    product = get_object_or_404(Product, id=id)
    serializer = ProductUpdateSerializer(instance=product, data=request.data)
    serializer.is_valid(raise_exception=True)
    serializer.save()
    return Response(serializer.data)

@api_view(["PATCH"]) # Lazim olan sutunlari update etmek olar. // partial=True olmalidir
def product_update_patch_view(request, id):
    product = get_object_or_404(Product, id=id)
    serializer = ProductUpdateSerializer(instance=product, data=request.data, partial=True)
    serializer.is_valid(raise_exception=True)
    serializer.save()
    return Response(serializer.data)
# ------------------------------------------------------------------------------

   

product/templates/product/partials/footer.html
{% load static %}

<footer class="footer-area">
	<div class="footer-widget">
		<div class="container">
			<div class="row footer-widget-wrapper pt-100 pb-70">
				<div class="col-md-6 col-lg-3">
					<div class="footer-widget-box about-us">
						<a href="index.html#" class="footer-logo">
							<img src="{% static 'product/assets/img/logo/logo-light.png' %}" alt="">
						</a>
						<p class="mb-1">
							We are many variations of the passages available but the majoro have suffered alteration
							in some form by injected.
						</p>
						<div class="footer-call">
							<div class="footer-call-icon">
								<i class="fal fa-headset"></i>
							</div>
							<div class="footer-call-info">
								<p>24/7 Need Any Help?</p>
								<a href="tel:+21236547898">(+2) 222 666 7777</a>
							</div>
						</div>
						<div class="footer-download">
							<h5>Get Our Mobile App</h5>
							<div class="footer-download-btn">
								<a href="index.html#">
									<i class="fab fa-google-play"></i>
									<div class="download-btn-info">
										<span>Get It On</span>
										<h6>Google Play</h6>
									</div>
								</a>
								<a href="index.html#">
									<i class="fab fa-app-store"></i>
									<div class="download-btn-info">
										<span>Get It On</span>
										<h6>App Store</h6>
									</div>
								</a>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-6 col-lg-2">
					<div class="footer-widget-box list">
						<h4 class="footer-widget-title">Quick Links</h4>
						<ul class="footer-list">
							<li><a href="index.html#">About Us</a></li>
							<li><a href="index.html#">Become A Seller</a></li>
							<li><a href="index.html#">Contact Us</a></li>
							<li><a href="index.html#">Update News</a></li>
							<li><a href="index.html#">Testimonials</a></li>
							<li><a href="index.html#">Terms Of Service</a></li>
							<li><a href="index.html#">Privacy policy</a></li>
						</ul>
					</div>
				</div>
				<div class="col-md-6 col-lg-2">
					<div class="footer-widget-box list">
						<h4 class="footer-widget-title">Browse Category</h4>
						<ul class="footer-list">
							<li><a href="index.html#">Accessories</a></li>
							<li><a href="index.html#">Home & Garden</a></li>
							<li><a href="index.html#">Electronics</a></li>
							<li><a href="index.html#">Health & Beauty</a></li>
							<li><a href="index.html#">Groceries</a></li>
							<li><a href="index.html#">Baby Toys</a></li>
							<li><a href="index.html#">Music & Video</a></li>
						</ul>
					</div>
				</div>
				<div class="col-md-6 col-lg-2">
					<div class="footer-widget-box list">
						<h4 class="footer-widget-title">Support Center</h4>
						<ul class="footer-list">
							<li><a href="index.html#">FAQ's</a></li>
							<li><a href="index.html#">How To Buy</a></li>
							<li><a href="index.html#">Support Center</a></li>
							<li><a href="index.html#">Track Your Order</a></li>
							<li><a href="index.html#">Returns Policy</a></li>
							<li><a href="index.html#">Our Affiliates</a></li>
							<li><a href="index.html#">Sitemap</a></li>
						</ul>
					</div>
				</div>
				<div class="col-md-6 col-lg-3">
					<div class="footer-widget-box list">
						<h4 class="footer-widget-title">Get In Touch</h4>
						<p>Feel Free To Get In Touch With Us Today. We Are Ready To Help You.</p>
						<ul class="footer-contact">
							<li><a href="tel:+21236547898"><i class="far fa-phone"></i>+2 123 654 7898</a></li>
							<li><i class="far fa-map-marker-alt"></i>25/B Milford Road, New York</li>
							<li><a href="../cdn-cgi/l/email-protection.html#731a1d151c33160b121e031f165d101c1e"><i class="far fa-envelope"></i><span class="__cf_email__" data-cfemail="8fe6e1e9e0cfeaf7eee2ffe3eaa1ece0e2">[email&#160;protected]</span></a></li>
							<li><i class="far fa-clock"></i>Mon-Fri (9.00AM - 8.00PM)</li>
						</ul>
					</div>
				</div>
				<div class="col-12">
					<div class="footer-top-link">
						<h5>Top Links</h5>
						<div class="footer-top-link-info">
							<a href="index.html#">Top Sellers</a>
							<a href="index.html#">New Arrivals</a>
							<a href="index.html#">Accessories</a>
							<a href="index.html#">Electronics</a>
							<a href="index.html#">Groceries</a>
							<a href="index.html#">Beauty</a>
							<a href="index.html#">Health</a>
							<a href="index.html#">Baby Toys</a>
							<a href="index.html#">Music</a>
							<a href="index.html#">Furniture</a>
							<a href="index.html#">Gifts</a>
							<a href="index.html#">Sports</a>
							<a href="index.html#">Automotive</a>
							<a href="index.html#">Watch</a>
							<a href="index.html#">Sitemap</a>
							<a href="index.html#">Our Affiliates</a>
							<a href="index.html#">Returns Policy</a>
							<a href="index.html#">Video</a>
							<a href="index.html#">Home & Garden</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="copyright">
		<div class="container">
			<div class="copyright-wrap">
				<div class="row">
					<div class="col-12 col-lg-4 align-self-center">
						<div class="footer-payment">
							<span>We Accept:</span>
							<img src="{% static 'product/assets/img/payment/visa.svg' %}" alt="">
							<img src="{% static 'product/assets/img/payment/mastercard.svg' %}" alt="">
							<img src="{% static 'product/assets/img/payment/amex.svg' %}" alt="">
							<img src="{% static 'product/assets/img/payment/discover.svg' %}" alt="">
							<img src="{% static 'product/assets/img/payment/paypal.svg' %}" alt="">
						</div>
					</div>
					<div class="col-12 col-lg-4 align-self-center">
						<p class="copyright-text">
							&copy; Copyright <span id="date"></span> <a href="index.html#"> Goemart </a> All Rights Reserved.
						</p>
					</div>
					<div class="col-12 col-lg-4 align-self-center">
						<div class="footer-social">
							<span>Follow Us:</span>
							<a href="index.html#"><i class="fab fa-facebook-f"></i></a>
							<a href="index.html#"><i class="fab fa-twitter"></i></a>
							<a href="index.html#"><i class="fab fa-linkedin-in"></i></a>
							<a href="index.html#"><i class="fab fa-youtube"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</footer>

product/templates/product/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="keywords" content="">
<title>Goemart - {{ page_title }}</title>
<link rel="icon" type="image/x-icon" href="{% static 'product/assets/img/logo/favicon.png' %}">
<link rel="stylesheet" href="{% static 'product/assets/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'product/assets/css/all-fontawesome.min.css' %}">
<link rel="stylesheet" href="{% static 'product/assets/css/animate.min.css' %}">
<link rel="stylesheet" href="{% static 'product/assets/css/magnific-popup.min.css' %}">
<link rel="stylesheet" href="{% static 'product/assets/css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'product/assets/css/jquery-ui.min.css' %}">
<link rel="stylesheet" href="{% static 'product/assets/css/nice-select.min.css' %}">
<link rel="stylesheet" href="{% static 'product/assets/css/flex-slider.min.css' %}">
<link rel="stylesheet" href="{% static 'product/assets/css/style.css' %}">

product/templates/product/partials/middlebar.html
{% load static %}

<div class="header-middle">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-5 col-lg-3 col-xl-3">
				<div class="header-middle-logo">
					<a class="navbar-brand" href="{% url 'product:index' %}">
						<img src="{% static 'product/assets/img/logo/logo.png' %}" alt="logo">
					</a>
				</div>
			</div>
			<div class="d-none d-lg-block col-lg-6 col-xl-5">
				<div class="header-middle-search">
					<form action="index.html#">
						<div class="search-content">
							<select class="select">
								<option value="">All Category</option>
								<option value="1">Today's Hot Deals</option>
								<option value="2">Fashion & Accessories</option>
								<option value="3">Electronics</option>
								<option value="4">Grocery & Market</option>
								<option value="5">Music</option>
								<option value="6">Home & Furniture</option>
								<option value="7">Toy & Video Games</option>
								<option value="8">Gifts</option>
								<option value="9">Babies & Moms</option>
								<option value="10">Sports & Outdoor</option>
								<option value="11">Health & Beauty</option>
							</select>
							<input type="text" class="form-control" placeholder="Search Here...">
							<button type="submit" class="search-btn"><i class="far fa-search"></i></button>
						</div>
					</form>
				</div>
			</div>
			<div class="col-7 col-lg-3 col-xl-4">
				<div class="header-middle-right">
					<ul class="header-middle-list">
						<li><a href="index.html#" class="list-item"><i class="far fa-user-circle"></i></a></li>
						{% if request.user.is_authenticated  %}
							<li><a title="logout" href="{% url "product:logout" %}" class="list-item"><i class="far fa-sign-out"></i></a></li>
						{% else  %}
							<li><a title="login" href="{% url "product:login" %}" class="list-item"><i class="far fa-sign-in"></i></a></li>
						{% endif %}
						
						
						<li><a href="index.html#" class="list-item"><i class="far fa-heart"></i><span>0</span></a></li>
						<li class="dropdown-cart">
							<a href="index.html#" class="shop-cart list-item"><i class="far fa-shopping-bag"></i>
								<span>5</span></a>
							<div class="dropdown-cart-menu">
								<div class="dropdown-cart-header">
									<span>03 Items</span>
									<a href="index.html#">View Cart</a>
								</div>
								<ul class="dropdown-cart-list">
									<li>
										<div class="dropdown-cart-item">
											<div class="cart-img">
												<a href="index.html#"><img src="{% static 'product/assets/img/product/p47.png' %}" alt="#"></a>
											</div>
											<div class="cart-info">
												<h4><a href="index.html#">Xamaha R15 Red</a></h4>
												<p class="cart-qty">1x - <span class="cart-amount">$200.00</span></p>
											</div>
											<a href="index.html#" class="cart-remove" title="Remove this item"><i class="far fa-times-circle"></i></a>
										</div>
									</li>
									<li>
										<div class="dropdown-cart-item">
											<div class="cart-img">
												<a href="index.html#"><img src="{% static 'product/assets/img/product/p12.png' %}" alt="#"></a>
											</div>
											<div class="cart-info">
												<h4><a href="index.html#">Apple Blue Watch</a></h4>
												<p class="cart-qty">1x - <span class="cart-amount">$120.00</span></p>
											</div>
											<a href="index.html#" class="cart-remove" title="Remove this item"><i class="far fa-times-circle"></i></a>
										</div>
									</li>
									<li>
										<div class="dropdown-cart-item">
											<div class="cart-img">
												<a href="index.html#"><img src="{% static 'product/assets/img/product/p32.png' %}" alt="#"></a>
											</div>
											<div class="cart-info">
												<h4><a href="index.html#">Orange Sweater</a></h4>
												<p class="cart-qty">1x - <span class="cart-amount">$330.00</span></p>
											</div>
											<a href="index.html#" class="cart-remove" title="Remove this item"><i class="far fa-times-circle"></i></a>
										</div>
									</li>
								</ul>
								<div class="dropdown-cart-bottom">
									<div class="dropdown-cart-total">
										<span>Total</span>
										<span class="total-amount">$650.00</span>
									</div>
									<a href="index.html#" class="theme-btn">Checkout</a>
								</div>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>

product/templates/product/partials/preloader.html
<div class="preloader">
	<div class="loader-ripple">
		<div></div>
		<div></div>
	</div>
</div>

product/templates/product/partials/scripts.html
{% load static %}

<script src="{% static 'product/assets/js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'product/assets/js/modernizr.min.js' %}"></script>
<script src="{% static 'product/assets/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'product/assets/js/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static 'product/assets/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'product/assets/js/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'product/assets/js/jquery.appear.min.js' %}"></script>
<script src="{% static 'product/assets/js/jquery.easing.min.js' %}"></script>
<script src="{% static 'product/assets/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'product/assets/js/counter-up.js' %}"></script>
<script src="{% static 'product/assets/js/jquery-ui.min.js' %}"></script>
<script src="{% static 'product/assets/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'product/assets/js/countdown.min.js' %}"></script>
<script src="{% static 'product/assets/js/flex-slider.js' %}"></script>
<script src="{% static 'product/assets/js/wow.min.js' %}"></script>
<script src="{% static 'product/assets/js/main.js' %}"></script>

product/templates/product/partials/scroll.html
<a href="javascript:void(0);" id="scroll-top">
	<i class="far fa-arrow-up-from-arc"></i>
</a>

product/templates/product/partials/topbar.html
<div class="header-top">
	<div class="container">
		<div class="header-top-wrapper">
			<div class="row">
				<div class="col-12 col-md-6 col-lg-6 col-xl-5">
					<div class="header-top-left">
						<ul class="header-top-list">
							<li><a href="../cdn-cgi/l/email-protection.html#83eaede5ecc3e6fbe2eef3efe6ade0ecee"><i class="far fa-envelopes"></i>
									<span class="__cf_email__" data-cfemail="ddb4b3bbb29db8a5bcb0adb1b8f3beb2b0">[email&#160;protected]</span></a></li>
							<li><a href="tel:+21236547898"><i class="far fa-headset"></i> +2 123 654
									7898</a></li>
							<li class="help"><a href="index.html#"><i class="far fa-comment-question"></i> Need Help?</a></li>
						</ul>
					</div>
				</div>
				<div class="col-12 col-md-6 col-lg-6 col-xl-7">
					<div class="header-top-right">
						<ul class="header-top-list">
							<li><a href="index.html#"><i class="far fa-alarm-clock"></i> Daily Deal</a></li>
							<li class="account"><a href="index.html#"><i class="far fa-user-vneck"></i> Account</a></li>
							<li class="login"><a href="index.html#"><i class="far fa-arrow-right-to-arc"></i> Login</a></li>
							<li>
								<div class="dropdown">
									<a href="index.html#" class="dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
										<i class="far fa-usd"></i> USD
									</a>
									<div class="dropdown-menu">
										<a class="dropdown-item" href="index.html#">USD</a>
										<a class="dropdown-item" href="index.html#">EUR</a>
										<a class="dropdown-item" href="index.html#">AUD</a>
										<a class="dropdown-item" href="index.html#">CUD</a>
									</div>
								</div>
							</li>
							<li>
								<div class="dropdown">
									<a href="index.html#" class="dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
										<i class="far fa-globe-americas"></i> EN
									</a>
									<div class="dropdown-menu">
										<a class="dropdown-item" href="index.html#">EN</a>
										<a class="dropdown-item" href="index.html#">FR</a>
										<a class="dropdown-item" href="index.html#">DE</a>
										<a class="dropdown-item" href="index.html#">RU</a>
									</div>
								</div>
							</li>
							<li class="social">
								<div class="header-top-social">
									<span>Follow Us: </span>
									<a href="index.html#"><i class="fab fa-facebook"></i></a>
									<a href="index.html#"><i class="fab fa-twitter"></i></a>
									<a href="index.html#"><i class="fab fa-instagram"></i></a>
									<a href="index.html#"><i class="fab fa-linkedin"></i></a>
								</div>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>