core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from product.views import page_not_found

urlpatterns = [
    path("admin/", admin.site.urls),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("", include("product.urls", namespace="product")),

    path("api/product/", include("product.api.urls")),
]

handler404 = page_not_found

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/api/urls.py
from django.urls import path
from product.api.views import product_list_create_view, product_detail_view, index_view, product_create_view, product_delete_view, product_update_put_view, product_update_patch_view

app_name = "product/api"


urlpatterns = [
    path("products/", product_list_create_view, name="products_list_create"), # "GET", "POST"
    path("products/<int:id>", product_detail_view, name="products_detail"),   # "GET", "PUT", "PATCH", "DELETE"
]




# urlpatterns = [
#     path("index/", index_view, name="index"),
#     path("detail/<id>", product_detail_view, name="detail"),
#     path("delete/<id>", product_delete_view, name="delete"),
#     path("create/", product_create_view, name="create"),

#     path("update_put/<id>", product_update_put_view, name="update_put"),
#     path("update_patch/<id>", product_update_patch_view, name="update_patch"),
# ]

product/urls.py
from django.urls import path
from . import views

app_name = "product"

urlpatterns = [
    path("", views.index, name="index"),
    path("home/", views.home, name="home"),
    path("products/", views.product_list, name="product_list"),
    
    # path("products/<int:product_id>/", views.product_detail, name="product_detail"),
    path("products/<slug:slug>/", views.product_detail, name="product_detail"),

    path("products/add/", views.product_add, name="product_add"),
    path("categories/", views.category_list, name="category_list"),
    path("categories/<int:category_id>/", views.category_products, name="category_products"),

    # Usermodel
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register_view, name="register"),

    # Custom
    path("a_login/", views.a_login_view, name="a_login"),
    path("a_logout/", views.a_logout_view, name="a_logout"),
    path("a_register/", views.a_register_view, name="a_register"),
    
    path("a_send_change_password_email/", views.a_send_change_password_email, name="a_send_change_password_email"),
    path("a_confirm_change_password/<uuid:token>/", views.a_confirm_change_password, name="a_confirm_change_password"),



]

product/api/views.py
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework import status
from django.shortcuts import get_object_or_404
from rest_framework.response import Response
from .permissions import IsAuthorAuthenticated  # yuxarıda yazdığımız custom permission

# from product.api.serialize import ProductSerializer, ProductListSerializer, ProductCreateSerializer, ProductUpdateSerializer
from product.api.serialize import (
    ProductListSerializer,
    ProductCreateSerializer,
    ProductUpdateSerializer
)

from product.models import Author, Product
from django.db.models import FloatField, F, ExpressionWrapper, Value, DecimalField
from django.db.models.functions import Coalesce, Round

def annotate_products():
    return Product.objects.annotate(
        discount_price=Coalesce('discount', Value(0), output_field=FloatField()),
        coupon_price=Coalesce('coupon', Value(0), output_field=FloatField()),
        tax=Coalesce('tax_price', Value(0), output_field=FloatField()),
        ).annotate(
        total_price=Round(
            ExpressionWrapper(
                (F('price') * (1 - F('discount_price') / 100) - F('coupon_price') + F('tax')),
                output_field=DecimalField(max_digits=10, decimal_places=2)
            ),
            precision=2
        )
    )

@api_view(["GET", "POST"])
# @permission_classes([IsAuthenticatedOrReadOnly])
@permission_classes([IsAuthorAuthenticated])  # indi bu istifadə olunacaq
def product_list_create_view(request):
    if request.method == "GET":
        products = annotate_products()
        serializer =  ProductListSerializer(products, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)
    
    elif request.method == "POST":
        serializer = ProductCreateSerializer(data=request.data)
        if serializer.is_valid():
        
            try:
                author_id = request.session.get("author_id")
                author = Author.objects.get(id=author_id)
            except (Author.DoesNotExist, TypeError):
                return Response({"error": "Author not found in session"}, status=404)

            serializer.save(author=author)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    

@api_view(["GET", "PUT", "PATCH", "DELETE"])
# @permission_classes([IsAuthorAuthenticated])  # indi bu istifadə olunacaq
def product_detail_view(request, id):
    pruduct = get_object_or_404(annotate_products(), id=id)
    
    if request.method == "GET":
        serializer = ProductListSerializer(pruduct)
        return Response(serializer.data, status=status.HTTP_200_OK)

    elif request.method in ["PUT", "PATCH"]:
        partial = request.method == "PATCH"  # True, False

        serializer = ProductUpdateSerializer(pruduct, data=request.data, partial=partial)

        if serializer.is_valid():
            serializer.save()
            #save olunduqdan sonra melumatlari ekrana cixarsin deye elave olunur
            pruduct = get_object_or_404(annotate_products(), id=id)
            serializer = ProductListSerializer(pruduct)
            return Response(serializer.data, status=status.HTTP_200_OK)
    
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == "DELETE":
        pruduct.delete()
        return Response({"message":"Mehsul ugurla silindi!"}, status=status.HTTP_204_NO_CONTENT)






















# GET, POST, PUT, PATCH, DELETE
# ------------------------------------------------------------------------------
@api_view(["GET"])
def index_view(request):
    # product = Product.objects.all()

    product = Product.objects.annotate(
        discount_price=Coalesce('discount', Value(0), output_field=FloatField()),
        coupon_price=Coalesce('coupon', Value(0), output_field=FloatField()),
        tax=Coalesce('tax_price', Value(0), output_field=FloatField()),
        ).annotate(
        total_price=Round(
            ExpressionWrapper(
                (F('price') * (1 - F('discount_price') / 100) - F('coupon_price') + F('tax')),
                output_field=DecimalField(max_digits=10, decimal_places=2)
            ),
            precision=2
        )
    )

    serializer =  ProductListSerializer(product, many=True)
    print(serializer.data)
    return Response(serializer.data)


@api_view(["GET"])
def product_detail_view(request, id):

    # product = Product.objects.all()
    
    product = Product.objects.annotate(
        discount_price=Coalesce('discount', Value(0), output_field=FloatField()),
        coupon_price=Coalesce('coupon', Value(0), output_field=FloatField()),
        tax=Coalesce('tax_price', Value(0), output_field=FloatField()),
        ).annotate(
        total_price=Round(
            ExpressionWrapper(
                (F('price') * (1 - F('discount_price') / 100) - F('coupon_price') + F('tax')),
                output_field=DecimalField(max_digits=10, decimal_places=2)
            ),
            precision=2
        )
    )

    product = product.get(id=id)
    
    serializer = ProductListSerializer(product, many=False)

    return Response(serializer.data)


@api_view(["POST"])
def product_create_view(request):
    serializer = ProductCreateSerializer(data=request.data)
    serializer.is_valid(raise_exception=True)
    serializer.save()

    return Response(serializer.data)

@api_view(["DELETE"])
def product_delete_view(request, id):
    product = Product.objects.annotate(
        discount_price=Coalesce('discount', Value(0), output_field=FloatField()),
        coupon_price=Coalesce('coupon', Value(0), output_field=FloatField()),
        tax=Coalesce('tax_price', Value(0), output_field=FloatField()),
        ).annotate(
        total_price=Round(
            ExpressionWrapper(
                (F('price') * (1 - F('discount_price') / 100) - F('coupon_price') + F('tax')),
                output_field=DecimalField(max_digits=10, decimal_places=2)
            ),
            precision=2
        )
    )

    product = product.get(id=id)

    product.delete()
    return Response({"Messege":"Product successfully deleted!"})

# ------------------------------------------------------------------------------

@api_view(["PUT"]) # Butun sutunlari update etmek lazimdir. // partial=True lazim deyil
def product_update_put_view(request, id):
    product = get_object_or_404(Product, id=id)
    serializer = ProductUpdateSerializer(instance=product, data=request.data)
    serializer.is_valid(raise_exception=True)
    serializer.save()
    return Response(serializer.data)

@api_view(["PATCH"]) # Lazim olan sutunlari update etmek olar. // partial=True olmalidir
def product_update_patch_view(request, id):
    product = get_object_or_404(Product, id=id)
    serializer = ProductUpdateSerializer(instance=product, data=request.data, partial=True)
    serializer.is_valid(raise_exception=True)
    serializer.save()
    return Response(serializer.data)
# ------------------------------------------------------------------------------

   

product/templates/product/a_change_password.html
sdsdsd

product/templates/product/a_change_password_confirm.html
{% extends "product/layouts/base.html" %}
{% load static %}

{% block content %}
        <!-- breadcrumb -->
        <div class="site-breadcrumb">
            <div class="site-breadcrumb-bg" style="background: url(assets/img/breadcrumb/01.jpg)"></div>
            <div class="container">
                <div class="site-breadcrumb-wrap">
                    <h4 class="breadcrumb-title">Login</h4>
                    <ul class="breadcrumb-menu">
                        <li><a href="index.html"><i class="far fa-home"></i> Home</a></li>
                        <li class="active">Login</li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- breadcrumb end -->

        <style>
            .errorlist li ul li{
                color:red!important;
                text-align: center;
                margin-bottom: 15px;
            }
        </style>

        <!-- login area -->
        <div class="login-area py-100">
            <div class="container">
                <div class="col-md-7 col-lg-5 mx-auto">
                    <div class="login-form">
                        <div class="login-header">
                            <img src="assets/img/logo/logo.png" alt="">
                            <p>Change password</p>
                        </div>
                        <form method="POST">
                            {% csrf_token %}
                            
                            {{ form.as_p }}
                            

                            {% comment %} {% if form.errors  %}
                                {{form.errors}}
                            {% endif %} {% endcomment %}

                            {% if messages %}
                                <ul class="mes">
                                    {% for message in messages %}
                                        <li>{{message}}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}

                            <br>
                            <div class="d-flex align-items-center">
                                <button type="submit" class="theme-btn"><i class="far fa-sign-in"></i> Submit</button>
                            </div>
                        </form>
                       
                    </div>
                </div>
            </div>
        </div>
        <!-- login area end -->

 

{% endblock content %}

product/templates/product/a_login.html
{% extends "product/layouts/base.html" %}
{% load static %}

{% block content %}
        <!-- breadcrumb -->
        <div class="site-breadcrumb">
            <div class="site-breadcrumb-bg" style="background: url(assets/img/breadcrumb/01.jpg)"></div>
            <div class="container">
                <div class="site-breadcrumb-wrap">
                    <h4 class="breadcrumb-title">Login</h4>
                    <ul class="breadcrumb-menu">
                        <li><a href="index.html"><i class="far fa-home"></i> Home</a></li>
                        <li class="active">Login</li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- breadcrumb end -->

        <style>
            .errorlist li ul li{
                color:red!important;
                text-align: center;
                margin-bottom: 15px;
            }
        </style>

        <!-- login area -->
        <div class="login-area py-100">
            <div class="container">
                <div class="col-md-7 col-lg-5 mx-auto">
                    <div class="login-form">
                        <div class="login-header">
                            <img src="assets/img/logo/logo.png" alt="">
                            <p>Author Login with your goemart account</p>
                        </div>
                        <form method="POST">
                            {% csrf_token %}
                            
                            {{form.as_p}}
                            

                            {% comment %} {% if form.errors  %}
                                {{form.errors}}
                            {% endif %} {% endcomment %}

                            {% if messages %}
                                <ul class="mes">
                                    {% for message in messages %}
                                        <li>{{message}}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}

                            <br>
                            <div class="d-flex align-items-center">
                                <button type="submit" class="theme-btn"><i class="far fa-sign-in"></i> Login</button>
                            </div>
                            <br>
                            <p class="text-center"><a href="{% url 'product:a_send_change_password_email' %}">Forgot password</a></p>

                            
                        </form>
                       
                    </div>
                </div>
            </div>
        </div>
        <!-- login area end -->

 

{% endblock content %}

product/templates/product/a_register.html
{% extends "product/layouts/base.html" %}
{% load static %}

{% block content %}
        <!-- breadcrumb -->
        <div class="site-breadcrumb">
            <div class="site-breadcrumb-bg" style="background: url(assets/img/breadcrumb/01.jpg)"></div>
            <div class="container">
                <div class="site-breadcrumb-wrap">
                    <h4 class="breadcrumb-title">Login</h4>
                    <ul class="breadcrumb-menu">
                        <li><a href="index.html"><i class="far fa-home"></i> Home</a></li>
                        <li class="active">Login</li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- breadcrumb end -->

        <style>
            .errorlist li ul li{
                color:red!important;
                text-align: center;
                margin-bottom: 15px;
            }
        </style>

        <!-- login area -->
        <div class="login-area py-100">
            <div class="container">
                <div class="col-md-7 col-lg-5 mx-auto">
                    <div class="login-form">
                        <div class="login-header">
                            <img src="assets/img/logo/logo.png" alt="">
                            <p>Author Register with your goemart account</p>
                        </div>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            
                            {{form.as_p}}
                            

                            {% if form.errors  %}
                                {{form.errors}}
                            {% endif %}

                            

                            {% if messages %}
                                <ul class="mes">
                                    {% for message in messages %}
                                        <li>{{message}}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}

                            <br>
                            <div class="d-flex align-items-center">
                                <button type="submit" class="theme-btn"><i class="far fa-sign-in"></i> Register</button>
                            </div>
                        </form>
                       
                    </div>
                </div>
            </div>
        </div>
        <!-- login area end -->

 

{% endblock content %}

product/templates/product/category.html
{% extends "product/layouts/base.html" %}
{% load static %}

{% block content %}

<!-- breadcrumb -->
<div class="site-breadcrumb">
    <div class="site-breadcrumb-bg" style="background: url({% static 'product/assets/img/breadcrumb/01.jpg' %})"></div>
    <div class="container">
        <div class="site-breadcrumb-wrap">
            <h4 class="breadcrumb-title">Category One</h4>
            <ul class="breadcrumb-menu">
                <li><a href="index.html"><i class="far fa-home"></i> Home</a></li>
                <li class="active">Category One</li>
            </ul>
        </div>
    </div>
</div>
<!-- breadcrumb end -->

<!-- category area -->
<div class="category-area py-90">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="site-heading-inline">
                    <h2 class="site-title"><img src="{% static 'product/assets/img/icon/category.svg' %}" alt="">All Category</h2>
                </div>
            </div>
        </div>
        <div class="row g-2">
            {% for category in categories %}
            <div class="col-6 col-md-4 col-lg-2">
                <div class="category-item">
                    <a href="{{ category.get_absolute_url }}">
                        <div class="category-info">
                            <div class="icon">
                                {% if category.icon %}
                                <img src="{{ category.icon.url }}" alt="">
                                {% else %}
                                <img src="{% static 'product/assets/img/icon/no_image.svg' %}" alt="">
                                {% endif %}
                            </div>
                            <div class="content">
                                <h4>{{ category.name|truncatechars:20 }}</h4>
                                <p>{{ category.product_count }} Items</p>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- category area end-->

<!-- newsletter area -->
<div class="newsletter-area pt-60 pb-60">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 mx-auto">
                <div class="newsletter-content">
                    <h3>Get <span>20%</span> Off Discount Coupon</h3>
                    <p>By Subscribe Our Newsletter</p>
                    <div class="subscribe-form">
                        <form action="category.html#">
                            <input type="email" class="form-control" placeholder="Your Valid Email Address">
                            <button class="theme-btn" type="submit">
                                Subscribe <i class="far fa-paper-plane"></i>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="newsletter-img-1">
        <img src="{% static 'product/assets/img/newsletter/01.png' %}" alt="">
    </div>
    <div class="newsletter-img-2">
        <img src="{% static 'product/assets/img/newsletter/02.png' %}" alt="">
    </div>
</div>
<!-- newsletter area end -->

{% endblock %}

product/templates/product/login.html
{% extends "product/layouts/base.html" %}
{% load static %}

{% block content %}
        <!-- breadcrumb -->
        <div class="site-breadcrumb">
            <div class="site-breadcrumb-bg" style="background: url(assets/img/breadcrumb/01.jpg)"></div>
            <div class="container">
                <div class="site-breadcrumb-wrap">
                    <h4 class="breadcrumb-title">Login</h4>
                    <ul class="breadcrumb-menu">
                        <li><a href="index.html"><i class="far fa-home"></i> Home</a></li>
                        <li class="active">Login</li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- breadcrumb end -->

<style>
    .errorlist li ul li{
        color:red!important;
        text-align: center;
        margin-bottom: 15px;
    }
</style>
        <!-- login area -->
        <div class="login-area py-100">
            <div class="container">
                <div class="col-md-7 col-lg-5 mx-auto">
                    <div class="login-form">
                        <div class="login-header">
                            <img src="assets/img/logo/logo.png" alt="">
                            <p>Login with your goemart account</p>
                        </div>
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>{{form.username.label}}</label>
                                {{form.username}}
                                {% comment %} <input type="email" class="form-control" placeholder="Your Email"> {% endcomment %}
                            </div>
                            <div class="form-group">
                               <label>{{form.password.label}}</label>
                                {{form.password}}
                            </div>

                            {% if form.errors  %}
                                {{form.errors}}
                            {% endif %}
                        
                            <div class="d-flex align-items-center">
                                <button type="submit" class="theme-btn"><i class="far fa-sign-in"></i> Login</button>
                            </div>
                        </form>
                       
                    </div>
                </div>
            </div>
        </div>
        <!-- login area end -->


        <!-- newsletter area -->
        
        <!-- newsletter area end -->

 

{% endblock content %}

product/templates/product/product_add.html
{% extends "product/layouts/base.html" %}
{% load static %}

{% block content %}

<!-- breadcrumb -->
<div class="site-breadcrumb">
	<div class="site-breadcrumb-bg" style="background: url({% static 'product/assets/img/breadcrumb/01.jpg' %})"></div>
	<div class="container">
		<div class="site-breadcrumb-wrap">
			<h4 class="breadcrumb-title">Add Product</h4>
			<ul class="breadcrumb-menu">
				<li><a href="index.html"><i class="far fa-home"></i> Home</a></li>
				<li class="active">Add Product</li>
			</ul>
		</div>
	</div>
</div>
<!-- breadcrumb end -->

<!-- user add product -->
<div class="user-area bg py-100">
	<div class="container">
		<div class="row">
			<div class="col-lg-3">
				<div class="sidebar">
					<div class="sidebar-top">
						<div class="sidebar-profile-img">
							<img src="{% static 'product/assets/img/account/user.jpg' %}" alt="">
							<button type="button" class="profile-img-btn"><i class="far fa-camera"></i></button>
							<input type="file" class="profile-img-file">
						</div>
						<h5>Antoni Jonson</h5>
						<p><a href="../cdn-cgi/l/email-protection.html" class="__cf_email__" data-cfemail="22434c564d4c4b62475a434f524e470c414d4f">[email&#160;protected]</a></p>
					</div>
					<ul class="sidebar-list">
						<li><a href="vendor-dashboard.html"><i class="far fa-gauge-high"></i> Dashboard</a></li>
						<li><a href="vendor-profile.html"><i class="far fa-user"></i> My Profile</a></li>
						<li><a href="vendor-product.html"><i class="far fa-layer-group"></i> Products</a></li>
						<li><a class="active" href="vendor-add-product.html"><i class="far fa-upload"></i> Add New Product</a></li>
						<li><a href="vendor-order.html"><i class="far fa-shopping-bag"></i> All Orders <span class="badge badge-danger">02</span></a></li>
						<li><a href="vendor-payout.html"><i class="far fa-wallet"></i> Payout</a></li>
						<li><a href="vendor-transaction.html"><i class="far fa-credit-card"></i> Transaction</a></li>
						<li><a href="vendor-notification.html"><i class="far fa-bell"></i> Notification <span class="badge badge-danger">02</span></a></li>
						<li><a href="vendor-message.html"><i class="far fa-envelope"></i> Messages <span class="badge badge-danger">02</span></a></li>
						<li><a href="vendor-setting.html"><i class="far fa-gear"></i> Settings</a></li>
						<li><a href="vendor-add-product.html#"><i class="far fa-sign-out"></i> Logout</a></li>
					</ul>
				</div>
			</div>

			<div class="col-lg-9">
				<div class="user-wrapper">
					<div class="user-card">
						<div class="user-card-header">
							<h4 class="user-card-title">Add New Product</h4>
							<a href="vendor-product.html" class="theme-btn"><span class="far fa-arrow-left"></span>All Products</a>
						</div>
						<div class="col-lg-12">
							<div class="user-form">
								<h6 class="mb-20">Basic Information</h6>

								{% comment %} {% if form.errors  %}
								{{form.errors}}
								{% endif %} {% endcomment %}


								{% if form.errors %}
								<ul>
									{% for field, errors in form.errors.items %}
									{% for error in errors %}
									<li>{{ field }}: {{ error }}</li>
									{% endfor %}
									{% endfor %}
								</ul>
								{% endif %}

								<form method="POST" enctype="multipart/form-data">

									{% csrf_token %}

									{% comment %} {{form.as_p}} {% endcomment %}

									{% for field in form %}
									<label for="">{{field.label}}</label>
									{{field}}
									<br>
									{% endfor %}

									<button type="submit" class="btn btn-success">Send</button>
								</form>







								{% comment %} <form>
									{% csrf_token %}

									<div class="form-group mt-2">
										<label for="name">Name</label>
										<input type="text" name="name" class="form-control" placeholder="Add name" id="name">
									</div>

									<div class="form-group mt-2">
										<label for="price">Price</label>
										<input type="text" name="price" class="form-control" placeholder="Add price" id="price">
									</div>

									<button type="submit" class="btn btn-success">Send</button>
								</form> {% endcomment %}




							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- user add product end -->

{% endblock content %}

product/templates/product/register.html
{% extends "product/layouts/base.html" %}
{% load static %}

{% block content %}
        <!-- breadcrumb -->
        <div class="site-breadcrumb">
            <div class="site-breadcrumb-bg" style="background: url(assets/img/breadcrumb/01.jpg)"></div>
            <div class="container">
                <div class="site-breadcrumb-wrap">
                    <h4 class="breadcrumb-title">Register</h4>
                    <ul class="breadcrumb-menu">
                        <li><a href="index.html"><i class="far fa-home"></i> Home</a></li>
                        <li class="active">Register</li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- breadcrumb end -->

<style>
    .errorlist li ul li{
        color:red!important;
        text-align: center;
        margin-bottom: 15px;
    }
</style>
        <!-- login area -->
        <div class="login-area py-100">
            <div class="container">
                <div class="col-md-7 col-lg-5 mx-auto">
                    <div class="login-form">
                        <div class="login-header">
                            <img src="assets/img/logo/logo.png" alt="">
                            <p>Create your goemart account</p>
                        </div>
                        <form method="POST">
                            {% csrf_token %}
                            
                            {% for fields in form %}
                                <div class="form-group">
                                    <label>{{fields.label}}</label>
                                    {{fields}}
                                    {% comment %} <input type="email" class="form-control" placeholder="Your Email"> {% endcomment %}
                                </div>
                            {% endfor %}

                            {% if form.errors  %}
                                {{form.errors}}
                            {% endif %}
                        
                            <div class="d-flex align-items-center">
                                <button type="submit" class="theme-btn"><i class="far fa-sign-in"></i> Register</button>
                            </div>
                        </form>
                       
                    </div>
                </div>
            </div>
        </div>
        <!-- login area end -->


        <!-- newsletter area -->
        
        <!-- newsletter area end -->

 

{% endblock content %}